# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  host: localhost
  adapter: mysql2
  database: customizeit
  pool: 5
  timeout: 5000
  username: root
  password: 123

production:
  adapter: postgresql
  encoding: unicode
  database: d48in6vqs9162p
  pool: 5
  timeout: 5000
  username: kklkelnvkprcqv
  password: tuhg_7v55VL0kudI6EeeZR7x9G
  host: ec2-54-225-134-223.compute-1.amazonaws.com
  port: 5432
